'use client'

import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { ChatLayout } from '../components/ChatLayout'
import { LeftNav } from '../components/LeftNav'
import { ChatSidebar } from '../components/ChatSidebar'
import styles from './chat.module.css'

const NAV_CONTENT: Record<string, { title: string; description: string }> = {
  home: {
    title: 'Home',
    description: 'Welcome to your workspace. Use the assistant to get started.',
  },
  projects: {
    title: 'Projects',
    description: 'Manage your projects and track progress here.',
  },
  analytics: {
    title: 'Analytics',
    description:
      'View reports, metrics, and insights generated by the assistant.',
  },
  documents: {
    title: 'Documents',
    description: 'Access and manage documents and artifacts here.',
  },
  settings: {
    title: 'Settings',
    description: 'Configure workspace preferences and integrations.',
  },
}

export default function ChatPage() {
  const router = useRouter()
  const [activeNav, setActiveNav] = useState('home')
  const [userEmail, setUserEmail] = useState<string | undefined>(undefined)

  useEffect(() => {
    if (typeof window === 'undefined') return
    const raw = localStorage.getItem('aha_auth')
    if (!raw) {
      router.replace('/login')
      return
    }
    try {
      const data = JSON.parse(raw) as { email?: string }
      setUserEmail(data.email)
    } catch {
      router.replace('/login')
    }
  }, [router])

  const handleLogout = () => {
    localStorage.removeItem('aha_auth')
    router.replace('/login')
  }

  const content = NAV_CONTENT[activeNav] ?? NAV_CONTENT.home

  return (
    <ChatLayout
      leftNav={
        <LeftNav
          activeItem={activeNav}
          onSelect={setActiveNav}
          userEmail={userEmail}
          onLogout={handleLogout}
        />
      }
      rightSidebar={<ChatSidebar />}
    >
      <div className={styles.content}>
        <header className={styles.topbar}>
          <h2 className={styles.pageTitle}>{content.title}</h2>
          <span className={styles.badge}>Workspace</span>
        </header>

        <div className={styles.artifactArea}>
          <div className={styles.artifactPlaceholder}>
            <div className={styles.placeholderIcon} aria-hidden>
              ◫
            </div>
            <h3 className={styles.placeholderTitle}>Artifact Panel</h3>
            <p className={styles.placeholderDesc}>{content.description}</p>
            <p className={styles.placeholderHint}>
              Ask the assistant a question to generate content here.
            </p>
          </div>
        </div>
      </div>
    </ChatLayout>
  )
}
